remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Alessandro Cortese
logo: tmp_logo.png
description: Personal portfolio website.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
